name: octune
version: 0.2.0
github: "fengctor/octune"
license: BSD3
author: "Gary Feng"
maintainer: "gary.feng@uwaterloo.ca"
copyright: "2021 Gary Feng"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- data/*.wav

description: Please see the README on GitHub at <https://github.com/githubuser/octune#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- either
- lens
- megaparsec
- WAVE
- optparse-applicative
- monad-par

library:
  source-dirs: src

ghc-options:
- -Wall

executables:
  octune:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -O2
    dependencies:
    - octune

tests:
  octune-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - octune
