name: octune
version: 0.2.0
github: "fengctor/octune"
license: BSD3
author: "Gary Feng"
maintainer: "gary.feng@uwaterloo.ca"
copyright: "2021 Gary Feng"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- data/*.wav

description: Please see the README on GitHub at <https://github.com/githubuser/octune#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- dahdit >= 0.8
- dahdit-audio >= 0.8
- deepseq
- either
- lens
- megaparsec
- monad-par
- optparse-applicative
- primitive
- text
- proteaaudio

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  octune:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N2
    - -O2
    dependencies:
    - octune

tests:
  octune-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - octune
