resolver: lts-23.14

packages:
- .

allow-newer: true
allow-newer-deps:
- proteaaudio

extra-deps:
- aeson-via-0.2.3
- data-sword-0.2.0.3
- git: git@github.com:ejconlon/dahdit.git
  commit: 09567df7e301404e2d8879ee5e95258bf8dbc803
  subdirs:
  - dahdit
  - dahdit-audio
- proteaaudio-0.10.1
