resolver: lts-23.14

packages:
- .

allow-newer: true
allow-newer-deps:
- proteaaudio

extra-deps:
- aeson-via-0.2.3
- data-sword-0.2.0.3
- git: git@github.com:ejconlon/dahdit.git
  commit: f684369c5c4b951ce26f42dbb265c71d0b016e59
  subdirs:
  - dahdit
  - dahdit-audio
- proteaaudio-0.10.1
